### ISSUE TITLE
useSearchParams is changing twice after go back in browser history

### ISSUE THREAD

**Issue by mishimalisa** [solidjs/solid-app-router#108]
After setting a new search string, go back in the browser history and try to set it again, the search string will be changed twice. The first change will be the value that I'm trying to set and the second change will be the previous value.

I think the problem is because the reactive location.search is trying to re-execute. The solution would be wrap mergeSearchString with an untrack?

https://github.com/solidjs/solid-app-router/blob/92131af5bebce2f3993283349dcddf72f9506d75/src/routing.ts#L94-L97

**Comment by rturnq** [comment]
Thanks for pointing this out. It probably is a good idea to not track the `location.search` here in case `setSearchParams` is called from within a tracking scope like an effect. Ultimately the underlying problem appears to be in Solid itself, where the global reactive listener isn't getting cleaned up under a specific circumstance the router hits. This causes things to get tracked unexpectedly from otherwise inert scopes like an event handler.
