### ISSUE TITLE
Support optional path params

### ISSUE THREAD

**Issue by minht11** [solidjs/solid-app-router#24]
Add support for optional params so `/page` and `/page/unknown` both match in this example:
```jsx
<Route path="/page/:pathParam?" component={MyPage} />
```

**Comment by jceb** [comment]
Could this be implemented with a catchall page `/page/*.jsx`?

**Comment by N0tExisting** [comment]
> Could this be implemented with a catchall page `/page/*.jsx`?

@jceb yes, but it would also match `/page/something/else` instead of just `/page/something`

**Comment by elite174** [comment]
Guys, PLEASE, add this! Many people start using solid js with solid app router, but the router is not ready for production!

**Comment by ryansolid** [comment]
This is probably worth reviewing: https://github.com/remix-run/react-router/issues/7285#issuecomment-620071853

Ive never had optional path params in this sort of router for the past decade(back to Ember(. Looks like React Router 6 dropped support when they went this way too.

**Comment by boombang** [comment]
@ryansolid please checkout out https://github.com/solidjs/solid-app-router/issues/94.
There I had an issue with `useParams` and @rturnq said that `optional params is really what you want for handling this scenario` but `for the time being the best alternative is probably to use a splat (*)` that is also not the [best approach](https://github.com/solidjs/solid-app-router/issues/24#issuecomment-986963144)

**Comment by rturnq** [comment]
That React Router discussion is interesting and seems to show there is a lot of desire for it, or at least people are using the pattern for better or worse.

React Router and I assume React Location can mostly support the functionality by just specifying multiple routes and React's VDOM prevents extra work when navigating from one route to the other. For us, as it currently stands, specifying as sperate routes means navigating from one to the other will cause an unmount and remount.

Some options I've though about for handling this issue

1. Support optional parameters in path syntax: `path="foo/:id?"` or `path="foo/?id"` would match `/foo` and `/foo/123` but not `/foo/123/bar` unless a child route matched `bar`
2. Allow specifying multiple paths on a route `path={["foo", "foo/:id"]}` would match the same as 1 but would also let us match an arbitrary list of paths which could be helpful.
3. Keep path the same and use multiple route definitions but figure out how to identify them as equivalent to prevent the mount/unmount. This is tricky if we want to support `element` because we must not access that property until we are ready to render it. The other disadvantage is multiple route definitions make nested definitions duplicative.

These solutions are not mutually exclusive and adding one doesn't preclude us from the others. That said, I'm not sure yet what all the problems and corner-cases we will encounter if we do add one ore more of these.

**Comment by rturnq** [comment]
Version 0.4.0 adds support for optional parameters using the syntax `:param?` and also allows routes to specify multiple paths in an array.
