### ISSUE TITLE
Route Loads before the lazy Route Component Finishes fetching.

### ISSUE THREAD

**Issue by Nojus0** [solidjs/solid-app-router#49]
The path changes instantly but the Route component is still fetching, because of that, a flash of the blank page occurs.
How can I achieve a blocking way of fetching the Route Component, so when navigating to another lazy page it doesn't show a blank page but stays on the current one, and maybe shows a progress bar/line like on youtube by using a "hook" `useIsFetching(route?)`, I Looked into Data functions but I think it doesn't suit this use case because I just want to load a Route Component and no data alongside it.

Example ```https://codesandbox.io/s/solid-router-185j1```

**Comment by ryansolid** [comment]
Yeah the Router is built on a Fetch as you Render approach, which is purposefully unblocking. The trick is to use Suspense above the `<Routes>`. When loading the initial page you it can show a fallback, and when navigating the router has Transitions built in which will hold the current navigation from view and starting working offscreen. Your demo won't just work with Suspense because you put the slowdown inside the lazy component and that basically simulates data fetching that would be a resource, but if you just wrap the `<Routes>` component with Suspense your use case should be fine.

**Comment by Nojus0** [comment]
Thanks for explaining, I had no idea that wrapping `<Routes>` with `<Suspense>` would have that effect, I thought it would just show only the fallback when fetching the new Page. But it doesn't because of transitions. It swaps the Page/Components when all async stuff is done like fetching the component or `createResource`. In order for transitions to work, I need to wrap the surrounding component in a `<Suspense>`. That's how I now understand it. It would have been nice if this simple use case like navigating to a new page without the empty page flicker would have been described in the ReadMe, all I needed is to do is to wrap the `<Routes>` in a `<Suspense>`, but now I understand a lot better how Suspense and transitions work thanks a lot... a lot.... 😠.
