### ISSUE TITLE
Adding a title property to the route config to update the document title on navigation

### ISSUE THREAD

**Issue by davidjbeaver** [solidjs/solid-app-router#54]
Was reading some articles recently around SPA's and the issue of a document title when pages change.  I thought there might be an opportunity to add something into the router config to capture a page title (potentially combined with a "template" title for building a title of _site name - page name_ for example)

I was thinking something along the lines of having a router config property (and route component prop) of "title", which is then used during the navigation function to set the document title.  The "template" could be a top level config item (or even a property of the main Router object) which sets the template string and has some sort of placeholder that is replaced with the actual title to be updated.

I'm happy to look at getting a PR together to see if it could work, but just wanted to see if it's something that would be liked/supported.

**Comment by ryansolid** [comment]
Generally there is more than the title as well so we have dedicated libraries for this sort of thing like [solid-meta](https://www.npmjs.com/package/solid-meta). I've debated whether knowledge from the Router could let us do even better with this but not sure. It is something I've sort of figured I'd get around to thinking about at some point.

I think for now there is no benefit other than not needing another library and when I consider complexity around different things that could set the title (like async loading) or impact on things like server-side rendering probably not worth entangling this. I'm not completely sure but that's sort of where I'm at right now.

**Comment by nicholasdgoodman** [comment]
This is an old one, but I recently wanted to do something similar and just figured I would jot down my workaround in case someone else comes across this thread.

Essentially, I just created a wrapper for the `@solidjs/router` `Route` component that accepted a `title` property and added it accordingly.

```
import { Router, Route } from '@solidjs/router';
import { MetaProvider, Title } from '@solidjs/meta';

export function TitledRoute(props) {
  return (
    <Route {...props}
      component={() => (
        <MetaProvider><Title>{props.title}</Title>
          {props.component}
        </MetaProvider>
      )}
    />
  );
}
```

Then used it instead of `Route` on my router definition:

```
function App() {
  return (
    <Router root={Layout} >
      <TitledRoute path="/" title="Welcome" component={Home} />
      <TitledRoute path="/about" title="About" component={About} />
    </Router>
  );
}
```

@ryansolid - although this is an ancient issue, one way that I would have preferred to see it would be to have some means of passing additional usable props to the `root` component of the `Router`, that way we could put our `MetaProvider`, `Title`, etc. in the root Layout, which seems more natural, imo.
