### ISSUE TITLE
Autowire routes based on a predefined folder

### ISSUE THREAD

**Issue by theArtechnology** [solidjs/solid-app-router#62]
It would be interesting to have a feature like this:
```jsx
    <Router autowire={true} root={process.env.PUBLIC_URL}>
      <Nav />
      <Route class="view" />
    </Router>
```

Which takes a predefined (hard-coded) folder, let's say "pages" (since I've seen it on every solid projects. It will parse this folder and get `path.jsx/tsx` with its `path.data.js/ts` and generate the routes

**Comment by ryansolid** [comment]
Yeah I think it's a great feature but probably belongs outside the router itself. There are lot of opinonated ways to handle this and some work better with different bundler technologies since for development environments the bundler would need to be aware. I did create something for SolidStart, and I've seen some general Babel or Vite plugins. Technically our router works with them I believe. But I think it's more of a plugin rather than something that is core.

**Comment by theArtechnology** [comment]
Indeed, I do believe also that this feature resides  outside of this project, but talking about SolidStart, I was thinking in terms of SSR (sorry if I did not mentioned that earlier).

It would be a great boost in productivity without writing by hands the routes.
