### ISSUE TITLE
useMatch is not consistence with classList

### ISSUE THREAD

**Issue by harshmangalam** [solidjs/solid-app-router#72]
```
 <Link
      href="/about"
      classList={{
        "bg-blue-100 hover:bg-blue-100": Boolean(useMatch(() => "/about")()),
      }}
      className="rounded-full hover:bg-gray-100 px-2 py-1"
    >
     

      <span className="text-sm font-bold">About Us</span>
    </Link>
```

Refresh on /about path do not apply classList

**Comment by ryansolid** [comment]
It's hard to make guarentees on prop order and with two different props writing to the same underlying value we have our problem.

In this case I suspect you can just reverse it. `className` says set the className to this value and classList is more granular.  Since className comes after classList it just wipes it out. But there are cases where they can update independently based on their dependencies.

I think this is a design flaw of `classList` one that I want to address in the future if possible. But for now I recommend not using them on the same element/component if they are both dynamic or putting `class` or `className` first where possible.
