### ISSUE TITLE
Following a Link to a new route does not scroll to page top

### ISSUE THREAD

**Issue by maxmilton** [solidjs/solid-app-router#9]
Clicking on a `<Link href="..." />` and changing routes does not scroll to the top of the page, much like a regular link on a normal multi-page website.

As [a reference, `sapper`](https://github.com/sveltejs/sapper/blob/master/runtime/src/app/router/index.ts#L201) for example, will `scrollTo` top on new routes and also maintains a history of previous scroll position in case the user goes back/forward. [`vue-router` seems to](https://github.com/vuejs/vue-router/blob/dev/src/util/scroll.js) do the same thing.

**Comment by MaxMilton** [comment]
As a side note, for now I'm getting around this with:

```js
const oldHistoryPush = history.pushState;
history.pushState = function () {
  oldHistoryPush.apply(this, arguments);
  scrollTo(0, 0);
};
```

as [mentioned as a workaround in `preact-router`](https://github.com/preactjs/preact-router/issues/319#issuecomment-543838895).

**Comment by ryansolid** [comment]
Interesting. I was much of the opinion of Jason. I didn't think this is behavior that could be assumed. But interested if sapper and vue did so. Sapper does seem to by default. You have to set a property for it not to.

Honestly I never would have expected this behavior but I will take a look around. The other consideration is it is a side effect so would need figure out how to best schedule it under Suspense etc..

**Comment by MaxMilton** [comment]
Looking around more, I was interested to find `react-router` doesn't provide an out-of-the-box solution either but do have [documentation with app implementation suggestions](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md).

On the other extreme, Svelte kit (the successor to Sapper) has [yet another approach](https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/router.js) where they maintain scroll position in history with a rather heavy handed approach of listening to the `scroll` event.

**Comment by YamiteruXYZ** [comment]
I think the challenge here is to make it work with async fetching. Maybe if everything was wrapped in `Suspense` we could listen to it and trigger `scrollTo` and scroll to the remembered position when the content is loaded. However that's not ideal when it comes to UX, because the content might take a second to load and user might already start scrolling. So the scroll callback should cancel once user starts scrolling.

We can put the remembering of position logic into onClick of `Link` component before it pushes the new route.

**Comment by YamiteruXYZ** [comment]
So this is how I do it for now. I have this file:
```typescript
const data = <{ [key: string]: number }>{};

export const setScroll = () => {
  data[window.location.pathname] = window.scrollY || window.pageYOffset;
}

export const getScroll = (url: string) =>
  data[url] | 0;
```

I've added `setScroll()` in the `Link` component after `e.preventDefault()`.

In my `src/index.ts` I call `setScroll()`.

And I've added this in the first component under `<Router>`:
```typescript
const [router] = useRouter();

createEffect(() => {
  const y = getScroll(router.location);

  setTimeout(() =>
    window.scrollTo(0, y), 1);
})
```

The 1ms hack is there because when it's executed immediately it sometimes doesn't work.

I think that executing this effect should depend on how you fetch data. Since I have local only data and I'm planning on making it into SSG I don't have to care about that for now.

**Comment by ryansolid** [comment]
What's the desired behavior here? Push/pop state seems to retain scroll position so if I scrollTo 0 on new page navigation I go to the top.. pressing back takes to where I was. If I scroll on that new page and press back then forward I end up where I scrolled to. As long as I use browser buttons forward/back I preserve scroll. New navigation to the top. This mirrors native browser behavior. Is anything else desired? I don't understand why all this other stuff is being done. Using hackernews example for both Solid and Marko. In any case I will release this simple behavior that ties into the transitions.

**Comment by YamiteruXYZ** [comment]
Desired behaviour is to scroll to a remembered position even when user clicks a link in navigation.

Imagine a simple site with portfolio list and portfolio detail. When user scrolls to a certain position and opens an item they have 2 ways to go back.

1. Hit back button
2. Click on link navigating them back to the list

In both cases I want to retain the scroll position. A lot of people, usually but not always older people, click links and images more than back/forward, but they expect the same behaviour.

**Comment by ryansolid** [comment]
I see.. native browser doesn't do that. So I feel that would have to be opt in. Mind you I tend to bake popstate into my backwards navigation controls on the page (in case they came from different locations) so they still get that effect with it. Svelte HN I thought was built on Svelte Kit..but maybe Sapper seems to behave like the native browser. Are there other cases?

**Comment by YamiteruXYZ** [comment]
No, at least not for me.

**Comment by MaxMilton** [comment]
Thinking back on all the web-based apps I've made, the use case is so varied. For toy apps, relying on the browser default or a simple `scrollTo(0, 0)` was often enough, but for real apps, they have complex async loading and caching logic that needs special handling for scroll. Some even had custom scroll implementations (TV apps and other obscure devices which use web tech for UI), in which case scroll logic in a router would be unwanted.

The deeper I dive into this the more I'm inclined to think that scroll restoration should be defined in app logic rather than at the router level.

Sapper is built with svelte, but [SvelteKit](https://github.com/sveltejs/kit) is its own separate thing. Sapper, SvelteKit, Nuxt.js, Next.js, etc. _do_ include scroll restoration but it makes sense since they're web app frameworks.

vue-router is a bit special since it's a router that provides scroll logic but it's more feature-full overall than your typical router anyways. Looking through the code of many of the previous router packages I've used in the past, other than vue-router, none of them actually provide scroll restoration.

Feel free to close this issue if you think there's nothing to do.

History navigation and scroll are in the same thought space so I'm sure other developers will also have similar thinking as when I opened the issue. I suggest eventually including a note in the documentation that scroll restoration needs to be handled separately, perhaps with an example/s.

**Comment by ryansolid** [comment]
Well I added the scroll to 0 thing. It came up a few times now. This router is designed primarily for that SvelteKit like scenario. The other router from @rturnq is probably the one I'd recommend for the generic case. So this is exactly the place I'd be thinking about it. Scroll restoration on navigation does seem like something else. But I probably should have the means to disable the scroll to top so that can be done and leave it at that. Thanks for starting this interesting discussion.

**Comment by the-yamiteru** [comment]
I think scrolling to top should be optional

**Comment by ryansolid** [comment]
With the autoscrolling and the noScroll option I think we have this covered now. Closing.
