### ISSUE TITLE
useParams() with nested routes that don't have a component property

### ISSUE THREAD

**Issue by boombang** [solidjs/solid-app-router#94]
Hello!

I have the next component:
```js
const Home = () => {
  const params = useParams();

  return <h1>Home {params.id}</h1>;
};
```

And I want to render it for routes `/home` and `/home/:id`. So I use the next router config:
```js
const routes = [
  {
    path: "/home",
    component: Home,
    children: [{ path: "" }, { path: "/:id" }]
  }
];
``` 
But `useParams()` doesn't return `id`. Though it works fine with the next config where I cannot have  path `/home`:
```js
const routes = [
  {
    path: "/home/:id",
    component: Home
  }
];
```

Alternatively I can specify  `component: Home` directly in children but it causes full page rerender when I go from `/home` to `/home/1`:
```js
const routes = [
  {
    path: "/home",
    children: [
      { path: "", component: Home },
      { path: "/:id", component: Home }
    ]
  }
];
```

As I can see it can be resolved via this [proposal](https://github.com/solidjs/solid-app-router/issues/24). But what can be done for now?
[Link to repro](https://codesandbox.io/s/hungry-williamson-y2m2mf).
Thanks in advance!

**Comment by rturnq** [comment]
Yeah, optional params is really what you want for handling this scenario. For the time being the best alternative is probably to use a splat (*) to match the remaining path. Splats can be assigned to a parameter, so you could have a route like:
```js
{
  path: 'home/*id'
  component: Home
}
```
[Example](https://codesandbox.io/s/brave-fog-fz1r8b)

The biggest problem with this approach is splat routes can't have nested children since they consume the remaining path; however, they have the lowest matching priority so a sibling route can continue to work. If you need child routes it would be possible to add another `<Routes>` component within Home to manage it.

**Comment by boombang** [comment]
@rturnq thank you!
